// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Product", "Catalog");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description for product 1",
                            Name = "Prodcut 1",
                            Price = 716.02m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description for product 2",
                            Name = "Prodcut 2",
                            Price = 865.09m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description for product 3",
                            Name = "Prodcut 3",
                            Price = 926.47m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description for product 4",
                            Name = "Prodcut 4",
                            Price = 376.61m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description for product 5",
                            Name = "Prodcut 5",
                            Price = 530.53m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description for product 6",
                            Name = "Prodcut 6",
                            Price = 947.15m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description for product 7",
                            Name = "Prodcut 7",
                            Price = 655.57m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description for product 8",
                            Name = "Prodcut 8",
                            Price = 280.07m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description for product 9",
                            Name = "Prodcut 9",
                            Price = 215.49m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description for product 10",
                            Name = "Prodcut 10",
                            Price = 691.71m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Description for product 11",
                            Name = "Prodcut 11",
                            Price = 468.64m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Description for product 12",
                            Name = "Prodcut 12",
                            Price = 100.39m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Description for product 13",
                            Name = "Prodcut 13",
                            Price = 961.38m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Description for product 14",
                            Name = "Prodcut 14",
                            Price = 380.56m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Description for product 15",
                            Name = "Prodcut 15",
                            Price = 478.3m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Description for product 16",
                            Name = "Prodcut 16",
                            Price = 362.04m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Description for product 17",
                            Name = "Prodcut 17",
                            Price = 614.46m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Description for product 18",
                            Name = "Prodcut 18",
                            Price = 404.3m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Description for product 19",
                            Name = "Prodcut 19",
                            Price = 272.5m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Description for product 20",
                            Name = "Prodcut 20",
                            Price = 101.71m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Description for product 21",
                            Name = "Prodcut 21",
                            Price = 300.84m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Description for product 22",
                            Name = "Prodcut 22",
                            Price = 686.55m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Description for product 23",
                            Name = "Prodcut 23",
                            Price = 796.54m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Description for product 24",
                            Name = "Prodcut 24",
                            Price = 851.96m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Description for product 25",
                            Name = "Prodcut 25",
                            Price = 107.7m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Description for product 26",
                            Name = "Prodcut 26",
                            Price = 950.79m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Description for product 27",
                            Name = "Prodcut 27",
                            Price = 809.34m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Description for product 28",
                            Name = "Prodcut 28",
                            Price = 486.71m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Description for product 29",
                            Name = "Prodcut 29",
                            Price = 660.58m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Description for product 30",
                            Name = "Prodcut 30",
                            Price = 314.25m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Description for product 31",
                            Name = "Prodcut 31",
                            Price = 876.15m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Description for product 32",
                            Name = "Prodcut 32",
                            Price = 975.73m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Description for product 33",
                            Name = "Prodcut 33",
                            Price = 972.2m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Description for product 34",
                            Name = "Prodcut 34",
                            Price = 138.85m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Description for product 35",
                            Name = "Prodcut 35",
                            Price = 365.43m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Description for product 36",
                            Name = "Prodcut 36",
                            Price = 323.02m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Description for product 37",
                            Name = "Prodcut 37",
                            Price = 412.59m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Description for product 38",
                            Name = "Prodcut 38",
                            Price = 589.15m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Description for product 39",
                            Name = "Prodcut 39",
                            Price = 587.05m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Description for product 40",
                            Name = "Prodcut 40",
                            Price = 736.03m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Description for product 41",
                            Name = "Prodcut 41",
                            Price = 592.57m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Description for product 42",
                            Name = "Prodcut 42",
                            Price = 416.72m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Description for product 43",
                            Name = "Prodcut 43",
                            Price = 393.57m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Description for product 44",
                            Name = "Prodcut 44",
                            Price = 863.97m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Description for product 45",
                            Name = "Prodcut 45",
                            Price = 553.65m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Description for product 46",
                            Name = "Prodcut 46",
                            Price = 863.93m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Description for product 47",
                            Name = "Prodcut 47",
                            Price = 960.66m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Description for product 48",
                            Name = "Prodcut 48",
                            Price = 858.94m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Description for product 49",
                            Name = "Prodcut 49",
                            Price = 475.67m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Description for product 50",
                            Name = "Prodcut 50",
                            Price = 734.55m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Description for product 51",
                            Name = "Prodcut 51",
                            Price = 963.9m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Description for product 52",
                            Name = "Prodcut 52",
                            Price = 423.82m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Description for product 53",
                            Name = "Prodcut 53",
                            Price = 322.75m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Description for product 54",
                            Name = "Prodcut 54",
                            Price = 716.07m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Description for product 55",
                            Name = "Prodcut 55",
                            Price = 961.83m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Description for product 56",
                            Name = "Prodcut 56",
                            Price = 914.9m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Description for product 57",
                            Name = "Prodcut 57",
                            Price = 382.47m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Description for product 58",
                            Name = "Prodcut 58",
                            Price = 710.64m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Description for product 59",
                            Name = "Prodcut 59",
                            Price = 423.05m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Description for product 60",
                            Name = "Prodcut 60",
                            Price = 442.37m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Description for product 61",
                            Name = "Prodcut 61",
                            Price = 218.01m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Description for product 62",
                            Name = "Prodcut 62",
                            Price = 396.35m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Description for product 63",
                            Name = "Prodcut 63",
                            Price = 168.12m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Description for product 64",
                            Name = "Prodcut 64",
                            Price = 357.47m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Description for product 65",
                            Name = "Prodcut 65",
                            Price = 816.11m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Description for product 66",
                            Name = "Prodcut 66",
                            Price = 627.52m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Description for product 67",
                            Name = "Prodcut 67",
                            Price = 199.01m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Description for product 68",
                            Name = "Prodcut 68",
                            Price = 885.12m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Description for product 69",
                            Name = "Prodcut 69",
                            Price = 429.89m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Description for product 70",
                            Name = "Prodcut 70",
                            Price = 973.5m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Description for product 71",
                            Name = "Prodcut 71",
                            Price = 301.28m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Description for product 72",
                            Name = "Prodcut 72",
                            Price = 647.35m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Description for product 73",
                            Name = "Prodcut 73",
                            Price = 114.5m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Description for product 74",
                            Name = "Prodcut 74",
                            Price = 850.41m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Description for product 75",
                            Name = "Prodcut 75",
                            Price = 448.51m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Description for product 76",
                            Name = "Prodcut 76",
                            Price = 571.16m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Description for product 77",
                            Name = "Prodcut 77",
                            Price = 811.32m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Description for product 78",
                            Name = "Prodcut 78",
                            Price = 212.79m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Description for product 79",
                            Name = "Prodcut 79",
                            Price = 924.88m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Description for product 80",
                            Name = "Prodcut 80",
                            Price = 667.77m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Description for product 81",
                            Name = "Prodcut 81",
                            Price = 858.4m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Description for product 82",
                            Name = "Prodcut 82",
                            Price = 933.14m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Description for product 83",
                            Name = "Prodcut 83",
                            Price = 478.91m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Description for product 84",
                            Name = "Prodcut 84",
                            Price = 897.5m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Description for product 85",
                            Name = "Prodcut 85",
                            Price = 252.76m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Description for product 86",
                            Name = "Prodcut 86",
                            Price = 811.27m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Description for product 87",
                            Name = "Prodcut 87",
                            Price = 464.54m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Description for product 88",
                            Name = "Prodcut 88",
                            Price = 201.11m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Description for product 89",
                            Name = "Prodcut 89",
                            Price = 233.44m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Description for product 90",
                            Name = "Prodcut 90",
                            Price = 309.21m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Description for product 91",
                            Name = "Prodcut 91",
                            Price = 824.59m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Description for product 92",
                            Name = "Prodcut 92",
                            Price = 976.27m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Description for product 93",
                            Name = "Prodcut 93",
                            Price = 819.3m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Description for product 94",
                            Name = "Prodcut 94",
                            Price = 488.29m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Description for product 95",
                            Name = "Prodcut 95",
                            Price = 916.31m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Description for product 96",
                            Name = "Prodcut 96",
                            Price = 511.38m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Description for product 97",
                            Name = "Prodcut 97",
                            Price = 848m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Description for product 98",
                            Name = "Prodcut 98",
                            Price = 638.67m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Description for product 99",
                            Name = "Prodcut 99",
                            Price = 625.54m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "Description for product 100",
                            Name = "Prodcut 100",
                            Price = 322.92m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductInStockId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Stock", "Catalog");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductInStockId = 1,
                            Stock = 5
                        },
                        new
                        {
                            ProductId = 2,
                            ProductInStockId = 2,
                            Stock = 35
                        },
                        new
                        {
                            ProductId = 3,
                            ProductInStockId = 3,
                            Stock = 21
                        },
                        new
                        {
                            ProductId = 4,
                            ProductInStockId = 4,
                            Stock = 2
                        },
                        new
                        {
                            ProductId = 5,
                            ProductInStockId = 5,
                            Stock = 23
                        },
                        new
                        {
                            ProductId = 6,
                            ProductInStockId = 6,
                            Stock = 35
                        },
                        new
                        {
                            ProductId = 7,
                            ProductInStockId = 7,
                            Stock = 18
                        },
                        new
                        {
                            ProductId = 8,
                            ProductInStockId = 8,
                            Stock = 35
                        },
                        new
                        {
                            ProductId = 9,
                            ProductInStockId = 9,
                            Stock = 27
                        },
                        new
                        {
                            ProductId = 10,
                            ProductInStockId = 10,
                            Stock = 27
                        },
                        new
                        {
                            ProductId = 11,
                            ProductInStockId = 11,
                            Stock = 48
                        },
                        new
                        {
                            ProductId = 12,
                            ProductInStockId = 12,
                            Stock = 47
                        },
                        new
                        {
                            ProductId = 13,
                            ProductInStockId = 13,
                            Stock = 13
                        },
                        new
                        {
                            ProductId = 14,
                            ProductInStockId = 14,
                            Stock = 18
                        },
                        new
                        {
                            ProductId = 15,
                            ProductInStockId = 15,
                            Stock = 42
                        },
                        new
                        {
                            ProductId = 16,
                            ProductInStockId = 16,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 17,
                            ProductInStockId = 17,
                            Stock = 38
                        },
                        new
                        {
                            ProductId = 18,
                            ProductInStockId = 18,
                            Stock = 28
                        },
                        new
                        {
                            ProductId = 19,
                            ProductInStockId = 19,
                            Stock = 1
                        },
                        new
                        {
                            ProductId = 20,
                            ProductInStockId = 20,
                            Stock = 48
                        },
                        new
                        {
                            ProductId = 21,
                            ProductInStockId = 21,
                            Stock = 35
                        },
                        new
                        {
                            ProductId = 22,
                            ProductInStockId = 22,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 23,
                            ProductInStockId = 23,
                            Stock = 26
                        },
                        new
                        {
                            ProductId = 24,
                            ProductInStockId = 24,
                            Stock = 2
                        },
                        new
                        {
                            ProductId = 25,
                            ProductInStockId = 25,
                            Stock = 7
                        },
                        new
                        {
                            ProductId = 26,
                            ProductInStockId = 26,
                            Stock = 44
                        },
                        new
                        {
                            ProductId = 27,
                            ProductInStockId = 27,
                            Stock = 12
                        },
                        new
                        {
                            ProductId = 28,
                            ProductInStockId = 28,
                            Stock = 11
                        },
                        new
                        {
                            ProductId = 29,
                            ProductInStockId = 29,
                            Stock = 32
                        },
                        new
                        {
                            ProductId = 30,
                            ProductInStockId = 30,
                            Stock = 34
                        },
                        new
                        {
                            ProductId = 31,
                            ProductInStockId = 31,
                            Stock = 41
                        },
                        new
                        {
                            ProductId = 32,
                            ProductInStockId = 32,
                            Stock = 47
                        },
                        new
                        {
                            ProductId = 33,
                            ProductInStockId = 33,
                            Stock = 44
                        },
                        new
                        {
                            ProductId = 34,
                            ProductInStockId = 34,
                            Stock = 35
                        },
                        new
                        {
                            ProductId = 35,
                            ProductInStockId = 35,
                            Stock = 9
                        },
                        new
                        {
                            ProductId = 36,
                            ProductInStockId = 36,
                            Stock = 14
                        },
                        new
                        {
                            ProductId = 37,
                            ProductInStockId = 37,
                            Stock = 6
                        },
                        new
                        {
                            ProductId = 38,
                            ProductInStockId = 38,
                            Stock = 47
                        },
                        new
                        {
                            ProductId = 39,
                            ProductInStockId = 39,
                            Stock = 32
                        },
                        new
                        {
                            ProductId = 40,
                            ProductInStockId = 40,
                            Stock = 24
                        },
                        new
                        {
                            ProductId = 41,
                            ProductInStockId = 41,
                            Stock = 1
                        },
                        new
                        {
                            ProductId = 42,
                            ProductInStockId = 42,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 43,
                            ProductInStockId = 43,
                            Stock = 35
                        },
                        new
                        {
                            ProductId = 44,
                            ProductInStockId = 44,
                            Stock = 14
                        },
                        new
                        {
                            ProductId = 45,
                            ProductInStockId = 45,
                            Stock = 12
                        },
                        new
                        {
                            ProductId = 46,
                            ProductInStockId = 46,
                            Stock = 38
                        },
                        new
                        {
                            ProductId = 47,
                            ProductInStockId = 47,
                            Stock = 14
                        },
                        new
                        {
                            ProductId = 48,
                            ProductInStockId = 48,
                            Stock = 26
                        },
                        new
                        {
                            ProductId = 49,
                            ProductInStockId = 49,
                            Stock = 46
                        },
                        new
                        {
                            ProductId = 50,
                            ProductInStockId = 50,
                            Stock = 12
                        },
                        new
                        {
                            ProductId = 51,
                            ProductInStockId = 51,
                            Stock = 11
                        },
                        new
                        {
                            ProductId = 52,
                            ProductInStockId = 52,
                            Stock = 43
                        },
                        new
                        {
                            ProductId = 53,
                            ProductInStockId = 53,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 54,
                            ProductInStockId = 54,
                            Stock = 6
                        },
                        new
                        {
                            ProductId = 55,
                            ProductInStockId = 55,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 56,
                            ProductInStockId = 56,
                            Stock = 39
                        },
                        new
                        {
                            ProductId = 57,
                            ProductInStockId = 57,
                            Stock = 48
                        },
                        new
                        {
                            ProductId = 58,
                            ProductInStockId = 58,
                            Stock = 17
                        },
                        new
                        {
                            ProductId = 59,
                            ProductInStockId = 59,
                            Stock = 2
                        },
                        new
                        {
                            ProductId = 60,
                            ProductInStockId = 60,
                            Stock = 9
                        },
                        new
                        {
                            ProductId = 61,
                            ProductInStockId = 61,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 62,
                            ProductInStockId = 62,
                            Stock = 37
                        },
                        new
                        {
                            ProductId = 63,
                            ProductInStockId = 63,
                            Stock = 17
                        },
                        new
                        {
                            ProductId = 64,
                            ProductInStockId = 64,
                            Stock = 49
                        },
                        new
                        {
                            ProductId = 65,
                            ProductInStockId = 65,
                            Stock = 19
                        },
                        new
                        {
                            ProductId = 66,
                            ProductInStockId = 66,
                            Stock = 14
                        },
                        new
                        {
                            ProductId = 67,
                            ProductInStockId = 67,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 68,
                            ProductInStockId = 68,
                            Stock = 5
                        },
                        new
                        {
                            ProductId = 69,
                            ProductInStockId = 69,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 70,
                            ProductInStockId = 70,
                            Stock = 14
                        },
                        new
                        {
                            ProductId = 71,
                            ProductInStockId = 71,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 72,
                            ProductInStockId = 72,
                            Stock = 47
                        },
                        new
                        {
                            ProductId = 73,
                            ProductInStockId = 73,
                            Stock = 43
                        },
                        new
                        {
                            ProductId = 74,
                            ProductInStockId = 74,
                            Stock = 14
                        },
                        new
                        {
                            ProductId = 75,
                            ProductInStockId = 75,
                            Stock = 33
                        },
                        new
                        {
                            ProductId = 76,
                            ProductInStockId = 76,
                            Stock = 19
                        },
                        new
                        {
                            ProductId = 77,
                            ProductInStockId = 77,
                            Stock = 8
                        },
                        new
                        {
                            ProductId = 78,
                            ProductInStockId = 78,
                            Stock = 14
                        },
                        new
                        {
                            ProductId = 79,
                            ProductInStockId = 79,
                            Stock = 9
                        },
                        new
                        {
                            ProductId = 80,
                            ProductInStockId = 80,
                            Stock = 5
                        },
                        new
                        {
                            ProductId = 81,
                            ProductInStockId = 81,
                            Stock = 7
                        },
                        new
                        {
                            ProductId = 82,
                            ProductInStockId = 82,
                            Stock = 21
                        },
                        new
                        {
                            ProductId = 83,
                            ProductInStockId = 83,
                            Stock = 7
                        },
                        new
                        {
                            ProductId = 84,
                            ProductInStockId = 84,
                            Stock = 22
                        },
                        new
                        {
                            ProductId = 85,
                            ProductInStockId = 85,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 86,
                            ProductInStockId = 86,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 87,
                            ProductInStockId = 87,
                            Stock = 48
                        },
                        new
                        {
                            ProductId = 88,
                            ProductInStockId = 88,
                            Stock = 16
                        },
                        new
                        {
                            ProductId = 89,
                            ProductInStockId = 89,
                            Stock = 18
                        },
                        new
                        {
                            ProductId = 90,
                            ProductInStockId = 90,
                            Stock = 36
                        },
                        new
                        {
                            ProductId = 91,
                            ProductInStockId = 91,
                            Stock = 42
                        },
                        new
                        {
                            ProductId = 92,
                            ProductInStockId = 92,
                            Stock = 1
                        },
                        new
                        {
                            ProductId = 93,
                            ProductInStockId = 93,
                            Stock = 33
                        },
                        new
                        {
                            ProductId = 94,
                            ProductInStockId = 94,
                            Stock = 9
                        },
                        new
                        {
                            ProductId = 95,
                            ProductInStockId = 95,
                            Stock = 49
                        },
                        new
                        {
                            ProductId = 96,
                            ProductInStockId = 96,
                            Stock = 46
                        },
                        new
                        {
                            ProductId = 97,
                            ProductInStockId = 97,
                            Stock = 45
                        },
                        new
                        {
                            ProductId = 98,
                            ProductInStockId = 98,
                            Stock = 32
                        },
                        new
                        {
                            ProductId = 99,
                            ProductInStockId = 99,
                            Stock = 43
                        },
                        new
                        {
                            ProductId = 100,
                            ProductInStockId = 100,
                            Stock = 16
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
